name: Main
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  web-deploy:
    name: Wdrozenie do FTP
    runs-on: ubuntu-latest
    steps: 
    - name: Załadowanie kodu z Github
      users: actions/checkout@v3

    - name: Synchronizacja plików do serwera FTP
      users: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 20.127.233.250
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
